project_name: verbis
before:
  hooks:
    #- make all
    - go mod tidy
    - go generate ./...
builds:
  - id: "mac"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
archives:
  -
    id: mac
    builds:
      - mac
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: "verbis"
    files:
      - README.md
      - build/admin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
