# goreleaser for Verbis
project_name: Verbis
# Hooks to run before build
before:
  hooks:
    - echo {{.Version}}
    #- make all
    - go mod tidy
    - go generate ./...
    - cmd: cd admin && npm run build && cd ../
# Main Verbis build
builds:
  - id: "main"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    binary: verbis
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    tags:
      - prod
    ldflags:
      - -X 'github.com/ainsleyclark/verbis/api.ProductionString=true' -X 'github.com/ainsleyclark/verbis/api/version.Version={{.Version}}'
# Zip
archives:
  - builds:
      - main
    format: zip
    name_template: "{{ tolower .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: "verbis"
    files:
      - README.md
      - LICENSE
      - themes
      - src: .gitignore.build
        dst: .gitignore
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  skip: true
release:
  github:
    owner: ainsleyclark
    name: verbis
  name_template: "{{.ProjectName}} v{{.Version}}"
  draft: true
