project_name: Verbis
before:
  hooks:
    - make all
    - go mod tidy
    - go generate ./...
    - cmd: mv .gitignore .gitignore.bak
    - cmd: cp .gitignore.build .gitignore
after:
  hooks:
    - cmd: rm .gitignore
    - cmd: mv .gitignore.bak .gitignore
builds:
  - id: "main"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    tags:
      - prod
    ldflags:
      - -X 'github.com/ainsleyclark/verbis/api.ProductionString=true' -X 'github.com/ainsleyclark/verbis/api/version.Version={{.Version}}'
archives:
  -
    builds:
      - main
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: "verbis"
    files:
      - README.md
      - LICENSE
      - themes
      - .env.example
      - .gitignore
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: ainsleyclark
    name: verbis
  name_template: "{{.ProjectName}} v{{.Version}}"
  draft: true
