# |
# |--------------------------------------------------------------------------
# | Theme
# |--------------------------------------------------------------------------
# |
# | Include a title, description and version for your custom Verbis
# | theme here.
# |
# |
theme:
    title: Verbis
    description: How to Slep Theme for Verbis
    version: 0.0.1

# |
# |--------------------------------------------------------------------------
# | Resources
# |--------------------------------------------------------------------------
# |
# | Defines the resources to be used for the site. Each resource should
# | contain a name (key) a friendly name (for use within the admin)
# | a slug and an icon, if the icon is omitted, a default one
# | will be used.
# |
# |
resources:
    team:
        name: team
        friendly_name: Team Members
        singular_name: Team Member
        slug: /about-us
        icon: feather feather-user
        hidden: false
        hide_category_slug: true
        available_templates: [
                about-single
        ]
    guides:
        name: guides
        friendly_name: Guides
        singular_name: Guide
        slug: /guides
        icon: feather feather-inbox
        hidden: false
        hide_category_slug: true
        available_templates: [
                guide
        ]
    best-mattresses:
        name: best-mattresses
        friendly_name: Best Mattresses
        singular_name: Best Mattress
        slug: /best-mattresses
        icon: feather feather-cloud
        hidden: false
        hide_category_slug: true
        available_templates: [
                single
        ]
    best-pillows:
        name: best-pillows
        friendly_name: Best Pillows
        singular_name: Best Pillow
        slug: /best-pillows
        icon: feather feather-feather
        hidden: false
        hide_category_slug: true
        available_templates: [
                single
        ]
    mattress-reviews:
        name: mattress-reviews
        friendly_name: Mattress Reviews
        singular_name: Mattress Review
        slug: /mattress-reviews
        icon: feather feather-pie-chart
        hidden: false
        hide_category_slug: true
        available_templates: [
                single
        ]
    product-reviews:
        name: product-reviews
        friendly_name: Product Reviews
        singular_name: Product Review
        slug: /product-reviews
        icon: feather feather-clipboard
        hidden: false
        hide_category_slug: true
        available_templates: [
                single
        ]

# |
# |--------------------------------------------------------------------------
# | Assets Path
# |--------------------------------------------------------------------------
# |
# | The file path for the all static assets to be served by the CMS such as
# | images, fonts, favicon etc. is not resolved by the cms. Note - it
# | should not contain the file extension and is relative to the
# | theme's root.
# |
# |
assets_path: /assets

# |
# |--------------------------------------------------------------------------
# | File Extension
# |--------------------------------------------------------------------------
# |
# | The file extension of the files used to be created for templates
# | and partials etc.. The template extension can be anything,
# | for example - ".html, .cms, .tmpl" defaults to ".cms".
# |
# |
file_extension: .cms

# |
# |--------------------------------------------------------------------------
# | Template Directory
# |--------------------------------------------------------------------------
# |
# | Defines where the main templates reside relative to the theme's
# | path.
# |
# |
template_dir: templates

# |
# |--------------------------------------------------------------------------
# | Layout Directory
# |--------------------------------------------------------------------------
# |
# | Defines where the main layouts reside relative to the theme's
# | path.
# |
# |
layout_dir: layouts

# |
# |--------------------------------------------------------------------------
# | Admin
# |--------------------------------------------------------------------------
# |
# | Global Admin options
# |
# |
admin:
    # |
    # |--------------------------------------------------------------------------
    # | Admin Path
    # |--------------------------------------------------------------------------
    # |
    # | This dictates where the admin url will sit, and where the user will
    # | login. Defaults to "admin", but can be "dashboard" etc.
    # |
    # |
    admin_path: admin

    # |
    # |--------------------------------------------------------------------------
    # | Inactive Session Time
    # |--------------------------------------------------------------------------
    # |
    # | The amount of time in minutes for how long the user was last seen to
    # | them being ejected from the system.
    # |
    # |
    inactive_session_time: 480

# |
# |--------------------------------------------------------------------------
# | Media
# |--------------------------------------------------------------------------
# |
# | Global Media options
# |
# |
media:

    # |
    # |--------------------------------------------------------------------------
    # | Upload Path
    # |--------------------------------------------------------------------------
    # |
    # | The upload path defines where the media will be requested from the
    # | front-end of the website. For example, a file requested with the
    # | path "/uploads" would be similar to "/uploads/2020/09/photo.jpg"
    # |
    # |
    upload_path: /uploads

    # |
    # |--------------------------------------------------------------------------
    # | Allowed File Types
    # |--------------------------------------------------------------------------
    # |
    # | The upload path defines where the media will be requested from the
    # | front-end of the website. For example, a file requested with the
    # | path "/uploads" would be similar to "/uploads/2020/09/photo.jpg"
    # |
    # |
    allowed_file_types: [
            image/png,
            image/jpeg,
            image/gif,
            image/webp,
            image/bmp,
            image/svg+xml,
            video/mpeg,
            video/mp4,
            video/webm,
            application/pdf,
            application/msword,
    ]

# |
# |--------------------------------------------------------------------------
# | Editor
# |--------------------------------------------------------------------------
# |
# |
# |
# |
# |
# |
# |
editor:
    modules: [
            blockquote,
            code_block,
            code_block_highlight,
            code_view,
            hardbreak,
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
            paragraph,
            hr,
            ul,
            ol,
            bold,
            code,
            italic,
            link,
            strike,
            underline,
            history,
            search,
            trailing_node,
            color,
            table
    ]
    options:
        ul:
            class: list
        ol:
            class: list list-ordered
        link:
            rel: noopener noreferrer nofollow
        palette: [
                '#fad839',
                '#ca1f26',
                '#1b3990',
                '#333',
        ]