# |
# |--------------------------------------------------------------------------
# | Upload Path
# |--------------------------------------------------------------------------
# |
# | The upload path defines where the media will be requested from the
# | front-end of the website. For example, a file requested with the
# | path "/uploads" would be similar to "/uploads/2020/09/photo.jpg"
# |
# |
upload_path: /uploads

# |
# |--------------------------------------------------------------------------
# | Allowed File Types
# |--------------------------------------------------------------------------
# |
# | The upload path defines where the media will be requested from the
# | front-end of the website. For example, a file requested with the
# | path "/uploads" would be similar to "/uploads/2020/09/photo.jpg"
# |
# |
allowed_file_types: [
    image/png,
    image/jpeg,
    image/gif,
    image/webp,
    image/bmp,
    image/svg+xml,
    video/mpeg,
    video/mp4,
    video/webm,
    application/pdf,
    application/msword,
]