# |
# |--------------------------------------------------------------------------
# | Resources
# |--------------------------------------------------------------------------
# |
# | Defines the resources to be used for the site. Each resource should
# | contain a name (key) a friendly name (for use within the admin)
# | a slug and an icon, if the icon is omitted, a default one
# | will be used.
# |
# |
resources:
    posts:
        name: posts
        friendly_name: Posts
        slug: /posts
        icon: fa-toolbox
    news:
        name: news
        friendly_name: News
        slug: /news
        icon: fa-toolbox