name: Build

on:
    push:
        branches:
            - 'master'
        tags:
            - 'v*'
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: Set up Go
            uses: actions/setup-go@v2
            with:
                go-version: 1.16
        -   name: Run Tests
            run: make ci
        -   name: Upload coverage to Codecov
            uses: codecov/codecov-action@v1
            with:
                file: ./coverage.out
        -   name: Diff
            run: git diff
